/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Input: typeof import('./src/components/Input/index.vue')['default']
    SetBaseInformation: typeof import('./src/components/SetBaseInformation/index.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
  }
}
